[package]
name = "rustafarian-drone"
version = "0.1.0"
edition = "2021"

[dependencies]
wg_2024 = { git = "https://github.com/WGL-2024/WGL_repo_2024.git", features = ["serialize"] }
crossbeam="0.8"
toml="0.8"
crossbeam-channel="0.5"
rand="0.8"